# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "PWGlsIQebzonftIShGhIYZC/OOxdmaNtqPqtItO75JTtZtGFMi1IR1LPNVGREeYhctgl5FMt/7JvPRh9KF6Rdv2Ojoq7irG/gQH71sS3NXM/Sh611wpHivOk+5vN2lCLrAgxGcvBpRPpQUUba4UR5SEIRDBzVbifKamXUAdQwnVGGdfnBvdCPfXj6JxG9lvFdNeE20DLkWq1FSOLVLtvRklEHlb4zv/3HOFHEAV5KqVqvSGwPD+5ylGq8psrZS1pQpYe9npPnsGlPRXP4EcIXLGhNQ6pFNURTVNEjmLG7HxubMVxa+dyzrJ8P9YGoZjCJLQFr1Tb8m8I5HgDcfk+zJ3tkcCfNbRWDrMpFYiTtFLBvRCemU/nuemlMHdj5+1otbXyMdLZQQUySOdtbajYzXz4rFD4s1C1x7XdMx9ZNIzftrdKpEYa/FvIDpqVKuRZ9tOI9hSFWDD61XPqBcIhlyME4P6Xm4AY7JRfpoKtsUXK6kYq5Wgx0Me+UiZ7kWI6wxxHv/GhSuCIG8lARPwRFEAb46zuvyr0sAUE9Bkv6a5E1p7SkAqsVIDTlHZysGg44yx/x3JdI+L+yMNsaGYvXzN6cmh8YPRnfk+ZJbx19/iBxY2bu80YULkHcrfb1SLinX5tBvTmVyOkSh+QcCbJgVczJ1W3JXN7XNONIvn5TVM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
