# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "PWGlsIQebzonftIShGhIYZC/OOxdmaNtqPqtItO75JTtZtGFMi1IR1LPNVGREeYhctgl5FMt/7JvPRh9KF6Rdv2Ojoq7irG/gQH71sS3NXM/Sh611wpHivOk+5vN2lCLrAgxGcvBpRPpQUUba4UR5SEIRDBzVbifKamXUAdQwnVGGdfnBvdCPfXj6JxG9lvFdNeE20DLkWq1FSOLVLtvRklEHlb4zv/3HOFHEAV5KqVqvSGwPD+5ylGq8psrZS1pQpYe9npPnsGlPRXP4EcIXLGhNQ6pFNURTVNEjmLG7HxubMVxa+dyzrJ8P9YGoZjCJLQFr1Tb8m8I5HgDcfk+zJ3tkcCfNbRWDrMpFYiTtFLBvRCemU/nuemlMHdj5+1otbXyMdLZQQUySOdtbajYzXz4rFD4s1C1x7XdMx9ZNIzftrdKpEYa/FvIDpqVKuRZ9tOI9hSFWDD61XPqBcIhlyME4P6Xm4AY7JRfpoKtsUXK6kYq5Wgx0Me+UiZ7kWI6wxxHv/GhSuCIG8lARPwRFEAb46zuvyr0sAUE9Bkv6a5E1p7SkAqsVIDTlHZysGg44yx/x3JdI+L+yMNsaGYvXzN6cmh8YPRnfk+ZJbx19/iBxY2bu80YULkHcrfb1SLinX5tBvTmVyOkSh+QcCbJgVczJ1W3JXN7XNONIvn5TVM="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
