travis:
  secure:
    BINSTAR_TOKEN: PWGlsIQebzonftIShGhIYZC/OOxdmaNtqPqtItO75JTtZtGFMi1IR1LPNVGREeYhctgl5FMt/7JvPRh9KF6Rdv2Ojoq7irG/gQH71sS3NXM/Sh611wpHivOk+5vN2lCLrAgxGcvBpRPpQUUba4UR5SEIRDBzVbifKamXUAdQwnVGGdfnBvdCPfXj6JxG9lvFdNeE20DLkWq1FSOLVLtvRklEHlb4zv/3HOFHEAV5KqVqvSGwPD+5ylGq8psrZS1pQpYe9npPnsGlPRXP4EcIXLGhNQ6pFNURTVNEjmLG7HxubMVxa+dyzrJ8P9YGoZjCJLQFr1Tb8m8I5HgDcfk+zJ3tkcCfNbRWDrMpFYiTtFLBvRCemU/nuemlMHdj5+1otbXyMdLZQQUySOdtbajYzXz4rFD4s1C1x7XdMx9ZNIzftrdKpEYa/FvIDpqVKuRZ9tOI9hSFWDD61XPqBcIhlyME4P6Xm4AY7JRfpoKtsUXK6kYq5Wgx0Me+UiZ7kWI6wxxHv/GhSuCIG8lARPwRFEAb46zuvyr0sAUE9Bkv6a5E1p7SkAqsVIDTlHZysGg44yx/x3JdI+L+yMNsaGYvXzN6cmh8YPRnfk+ZJbx19/iBxY2bu80YULkHcrfb1SLinX5tBvTmVyOkSh+QcCbJgVczJ1W3JXN7XNONIvn5TVM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
