travis:
  secure:
    BINSTAR_TOKEN: msK3eQAnp8M/saFZN1YDg8One/bWe/4TfSFNlqX+mCQMsoqkj2wfUsFwc5SJj6BRGSyof4CdHT4KfneIGJW2FczPyjoe9yk2sfog7zbRcgMpy3/j+86wqIHVUoiYYA0KSAfzU6nIINHfo1n65WlQTObmHbJcZ3sDNSqygQttB/Y2JcyFvy6e9YwjaZOUbQh4uc4/H0IHyhY3XZ2B4H0+MFAlw+6VuqBrPodD+HcjGVuhvaaHON5IrM9QHZk8uZaEZeftkZ3Fp94EUtrRI/ynBWko0nI/A3Q7QT8h09OS2jc0wh7jE9ZHBauL6XTPd3xxgLkaMBEoEIuhCruuU0XyppYirrNEJ4Indw76S4tvxTPI+usUeXo9YtcDf/jYR+bd6gitRcYWZH1ju0JFvMNMgalWGE5NvxxGUr/mSXcvtcTlUSiJDzdQQpdqwXtXBMUuQlRtIT5xdnrtaHguWlKnQPk/wJy/m3rwBYGDH4U9XhupclY5JZsrHUIYm3z/IC7lZ3JWKst6ldGl8UiEDNdCPlwrRUd65W76CQfaEndMUxW7L5uUu1pq/7RmqT8UqR6RRQlLvvxzBl6LUaScWbTYHM3NhMJ0RTCi97QELEe22hcl5IYngM/J2ffUv8d5omHH2ymJxuqCum9uE0BPTYzRwt10cCPvKWpJraHvTogIx/A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
